var OA_output = new Array(); 
OA_output['Sidebar 1'] = '';
OA_output['Sidebar 1'] += "<"+"!--<"+"span class=\"declare\">Advertisement<"+"/span>-->\n";
OA_output['Sidebar 1'] += "<"+"div style=\"height:20px;\"><"+"/div><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5936__zoneid=40__OXLCA=1__cb=568614a37c__oadest=http%3A%2F%2Fwww.lightcms.com%2F%3Futm_source%3DSmashing%252B%28Sidebar%29%26utm_medium%3Dbanner%26utm_content%3DSwitcher%26utm_campaign%3DSmashing\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=switcher_w_title_w_logo_190_6.png&contenttype=png\' width=\'190\' height=\'400\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"div id=\'beacon_568614a37c\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=5936&amp;campaignid=2126&amp;zoneid=40&amp;loc=http%3A%2F%2Fcoding.smashingmagazine.com%2F2009%2F09%2F15%2Fthe-z-index-css-property-a-comprehensive-look%2F&amp;referer=http%3A%2F%2Fstackoverflow.com%2Fquestions%2F11856591%2Fhow-to-make-css-menu-stay-on-top&amp;cb=568614a37c\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['Sidebar 3'] = '';

OA_output['Medium Rectangle'] = '';
OA_output['Medium Rectangle'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5930__zoneid=22__OXLCA=1__cb=5d40231cce__oadest=http%3A%2F%2Fwww.lightcms.com%2F%3Futm_source%3DSmashing%252B%28Content%29%26utm_medium%3Dbanner%26utm_content%3DSwitcher%26utm_campaign%3DSmashing\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=switcher_w_title_w_logo_300_12.png&contenttype=png\' width=\'300\' height=\'250\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"div id=\'beacon_5d40231cce\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=5930&amp;campaignid=2124&amp;zoneid=22&amp;loc=http%3A%2F%2Fcoding.smashingmagazine.com%2F2009%2F09%2F15%2Fthe-z-index-css-property-a-comprehensive-look%2F&amp;referer=http%3A%2F%2Fstackoverflow.com%2Fquestions%2F11856591%2Fhow-to-make-css-menu-stay-on-top&amp;cb=5d40231cce\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['Logo'] = '';

OA_output['Textad'] = '';

OA_output['VIS 1'] = '';
OA_output['VIS 1'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4360__zoneid=70__OXLCA=1__cb=c3b34a8084__oadest=http%3A%2F%2Fw3-markup.com\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=banner_w3m_200x125.jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'PSD to HTML\' title=\'PSD to HTML\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4360__zoneid=70__OXLCA=1__cb=c3b34a8084__oadest=http%3A%2F%2Fw3-markup.com\' target=\'_blank\'>PSD to HTML<"+"/a><"+"div id=\'beacon_c3b34a8084\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4360&amp;campaignid=135&amp;zoneid=70&amp;loc=http%3A%2F%2Fcoding.smashingmagazine.com%2F2009%2F09%2F15%2Fthe-z-index-css-property-a-comprehensive-look%2F&amp;referer=http%3A%2F%2Fstackoverflow.com%2Fquestions%2F11856591%2Fhow-to-make-css-menu-stay-on-top&amp;cb=c3b34a8084\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['VIS 2'] = '';

OA_output['VIS 3'] = '';

OA_output['VIS 4'] = '';

OA_output['VIS 5'] = '';

OA_output['VIS 6'] = '';

OA_output['VIS 7'] = '';

OA_output['VIS 8'] = '';

OA_output['VIS 9'] = '';

OA_output['VIS 10'] = '';

OA_output['spnsr ROS 1'] = '';
OA_output['spnsr ROS 1'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5618__zoneid=24__OXLCA=1__cb=c08c34f2cb__oadest=http%3A%2F%2Fwww.stickermule.com%3Futm_campaign%3DSmashing_Branded%26utm_medium%3DBanner%26utm_source%3DSmashing_Mag\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=image_7.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Custom Stickers\' title=\'Custom Stickers\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5618__zoneid=24__OXLCA=1__cb=c08c34f2cb__oadest=http%3A%2F%2Fwww.stickermule.com%3Futm_campaign%3DSmashing_Branded%26utm_medium%3DBanner%26utm_source%3DSmashing_Mag\' target=\'_blank\'>Custom Stickers<"+"/a><"+"div id=\'beacon_c08c34f2cb\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=5618&amp;campaignid=1997&amp;zoneid=24&amp;loc=http%3A%2F%2Fcoding.smashingmagazine.com%2F2009%2F09%2F15%2Fthe-z-index-css-property-a-comprehensive-look%2F&amp;referer=http%3A%2F%2Fstackoverflow.com%2Fquestions%2F11856591%2Fhow-to-make-css-menu-stay-on-top&amp;cb=c08c34f2cb\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 2'] = '';
OA_output['spnsr ROS 2'] += "<"+"script src=\"http://bs.serving-sys.com/BurstingPipe/adServer.bs?cn=rsb&c=28&pli=6080755&PluID=0&w=200&h=125&86ced2f17e&ncu=http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5982__zoneid=24__OXLCA=1__cb=86ced2f17e__oadest=&wm=transparent&ucm=true\"><"+"/script>\n";
OA_output['spnsr ROS 2'] += "<"+"noscript>\n";
OA_output['spnsr ROS 2'] += "<"+"a href=\"http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5982__zoneid=24__OXLCA=1__cb=86ced2f17e__oadest=http%3A%2F%2Fbs.serving-sys.com%2FBurstingPipe%2FadServer.bs%3Fcn%3Dbrd%26FlightID%3D6080755%26Page%3D%26PluID%3D0%26Pos%3D9258\" target=\"_blank\"><"+"img src=\"http://bs.serving-sys.com/BurstingPipe/adServer.bs?cn=bsr&FlightID=6080755&Page=&PluID=0&Pos=9258\" border=0 width=200 height=125><"+"/a>\n";
OA_output['spnsr ROS 2'] += "<"+"/noscript>\n";
OA_output['spnsr ROS 2'] += "<"+"br><"+"a href=\"http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5982__zoneid=24__OXLCA=1__cb=86ced2f17e__oadest=http%3A%2F%2Fbs.serving-sys.com%2FBurstingPipe%2FadServer.bs%3Fcn%3Dbrd%26FlightID%3D6080749%26Page%3D%26PluID%3D0%26Pos%3D6429\" target=\"_blank\">Create free stunning sites!<"+"/a><"+"div id=\'beacon_86ced2f17e\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=5982&amp;campaignid=130&amp;zoneid=24&amp;loc=1&amp;referer=http%3A%2F%2Fcoding.smashingmagazine.com%2F2009%2F09%2F15%2Fthe-z-index-css-property-a-comprehensive-look%2F&amp;cb=86ced2f17e\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 3'] = '';
OA_output['spnsr ROS 3'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4588__zoneid=24__OXLCA=1__cb=38f501bac0__oadest=http%3A%2F%2Fmarkup-service.com%2F\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=banner_ms_smashing.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4588__zoneid=24__OXLCA=1__cb=38f501bac0__oadest=http%3A%2F%2Fmarkup-service.com%2F\' target=\'_blank\'>PSD to HTML5/CSS3<"+"/a><"+"div id=\'beacon_38f501bac0\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4588&amp;campaignid=1625&amp;zoneid=24&amp;loc=http%3A%2F%2Fcoding.smashingmagazine.com%2F2009%2F09%2F15%2Fthe-z-index-css-property-a-comprehensive-look%2F&amp;referer=http%3A%2F%2Fstackoverflow.com%2Fquestions%2F11856591%2Fhow-to-make-css-menu-stay-on-top&amp;cb=38f501bac0\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 4'] = '';
OA_output['spnsr ROS 4'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=2877__zoneid=24__OXLCA=1__cb=0112a30d2f__oadest=http%3A%2F%2Fwww.dreamtemplate.com%2F%3Fref%3Dsm\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=200x125-dt-2.gif&contenttype=gif\' width=\'200\' height=\'125\' alt=\'Premium Web Templates\' title=\'Premium Web Templates\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=2877__zoneid=24__OXLCA=1__cb=0112a30d2f__oadest=http%3A%2F%2Fwww.dreamtemplate.com%2F%3Fref%3Dsm\' target=\'_blank\'>Premium Web Templates<"+"/a><"+"div id=\'beacon_0112a30d2f\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=2877&amp;campaignid=1026&amp;zoneid=24&amp;loc=http%3A%2F%2Fcoding.smashingmagazine.com%2F2009%2F09%2F15%2Fthe-z-index-css-property-a-comprehensive-look%2F&amp;referer=http%3A%2F%2Fstackoverflow.com%2Fquestions%2F11856591%2Fhow-to-make-css-menu-stay-on-top&amp;cb=0112a30d2f\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 5'] = '';
OA_output['spnsr ROS 5'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5943__zoneid=24__OXLCA=1__cb=a06f7d8c25__oadest=http%3A%2F%2Fwww.lightcms.com%2F%3Futm_source%3DSmashing%252B%28Sponsor%29%26utm_medium%3Dbanner%26utm_content%3DSwitcher%252B%28Logo%252BOnly%29%26utm_campaign%3DSmashing\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=switcher_w_logo_200_10.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Create a Website. Build a Store.\' title=\'Create a Website. Build a Store.\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5943__zoneid=24__OXLCA=1__cb=a06f7d8c25__oadest=http%3A%2F%2Fwww.lightcms.com%2F%3Futm_source%3DSmashing%252B%28Sponsor%29%26utm_medium%3Dbanner%26utm_content%3DSwitcher%252B%28Logo%252BOnly%29%26utm_campaign%3DSmashing\' target=\'_blank\'>Create a Website. Build a Store.<"+"/a><"+"div id=\'beacon_a06f7d8c25\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=5943&amp;campaignid=2128&amp;zoneid=24&amp;loc=http%3A%2F%2Fcoding.smashingmagazine.com%2F2009%2F09%2F15%2Fthe-z-index-css-property-a-comprehensive-look%2F&amp;referer=http%3A%2F%2Fstackoverflow.com%2Fquestions%2F11856591%2Fhow-to-make-css-menu-stay-on-top&amp;cb=a06f7d8c25\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 6'] = '';
OA_output['spnsr ROS 6'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5753__zoneid=24__OXLCA=1__cb=04cd6bd554__oadest=http%3A%2F%2Fpsd2html.com%2F%3Futm_source%3Dsmashingmagazine.com%26utm_medium%3Dbanner%26utm_campaign%3Dnew-p2h\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=200x125_blue_7.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'PSD2HTML.com\' title=\'PSD2HTML.com\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5753__zoneid=24__OXLCA=1__cb=04cd6bd554__oadest=http%3A%2F%2Fpsd2html.com%2F%3Futm_source%3Dsmashingmagazine.com%26utm_medium%3Dbanner%26utm_campaign%3Dnew-p2h\' target=\'_blank\'>PSD2HTML.com<"+"/a><"+"div id=\'beacon_04cd6bd554\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=5753&amp;campaignid=1626&amp;zoneid=24&amp;loc=http%3A%2F%2Fcoding.smashingmagazine.com%2F2009%2F09%2F15%2Fthe-z-index-css-property-a-comprehensive-look%2F&amp;referer=http%3A%2F%2Fstackoverflow.com%2Fquestions%2F11856591%2Fhow-to-make-css-menu-stay-on-top&amp;cb=04cd6bd554\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 7'] = '';
OA_output['spnsr ROS 7'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5903__zoneid=24__OXLCA=1__cb=8083402960__oadest=http%3A%2F%2Fwww.zoho.com%2Fprojects%2Flp%2Fproject-management-and-collaboration.html\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=200x125-projects-122712_10.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Online Project Management\' title=\'Online Project Management\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5903__zoneid=24__OXLCA=1__cb=8083402960__oadest=http%3A%2F%2Fwww.zoho.com%2Fprojects%2Flp%2Fproject-management-and-collaboration.html\' target=\'_blank\'>Online Project Management<"+"/a><"+"div id=\'beacon_8083402960\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=5903&amp;campaignid=2113&amp;zoneid=24&amp;loc=http%3A%2F%2Fcoding.smashingmagazine.com%2F2009%2F09%2F15%2Fthe-z-index-css-property-a-comprehensive-look%2F&amp;referer=http%3A%2F%2Fstackoverflow.com%2Fquestions%2F11856591%2Fhow-to-make-css-menu-stay-on-top&amp;cb=8083402960\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 8'] = '';
OA_output['spnsr ROS 8'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5894__zoneid=24__OXLCA=1__cb=adf7f04c61__oadest=http%3A%2F%2Fwww.vectorstock.com%2Ffree-vectors%3FSM%3D1\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=vs-free-smash-200x125-nu1267.gif&contenttype=gif\' width=\'200\' height=\'125\' alt=\'Free + Royalty Free Vector Art\' title=\'Free + Royalty Free Vector Art\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5894__zoneid=24__OXLCA=1__cb=adf7f04c61__oadest=http%3A%2F%2Fwww.vectorstock.com%2Ffree-vectors%3FSM%3D1\' target=\'_blank\'>Free + Royalty Free Vector Art<"+"/a><"+"div id=\'beacon_adf7f04c61\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=5894&amp;campaignid=2106&amp;zoneid=24&amp;loc=http%3A%2F%2Fcoding.smashingmagazine.com%2F2009%2F09%2F15%2Fthe-z-index-css-property-a-comprehensive-look%2F&amp;referer=http%3A%2F%2Fstackoverflow.com%2Fquestions%2F11856591%2Fhow-to-make-css-menu-stay-on-top&amp;cb=adf7f04c61\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 9'] = '';
OA_output['spnsr ROS 9'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5182__zoneid=24__OXLCA=1__cb=db6ffb56c1__oadest=http%3A%2F%2Fwww.typekit.com%2F%3Futm_source%3Dsmashingmagazine%26utm_medium%3DDisplay%26utm_content%3Dshwf120515%26utm_campaign%3DGeneral\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=typekit-ad-200x125-1_18.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Web fonts with Typekit\' title=\'Web fonts with Typekit\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5182__zoneid=24__OXLCA=1__cb=db6ffb56c1__oadest=http%3A%2F%2Fwww.typekit.com%2F%3Futm_source%3Dsmashingmagazine%26utm_medium%3DDisplay%26utm_content%3Dshwf120515%26utm_campaign%3DGeneral\' target=\'_blank\'>Web fonts with Typekit<"+"/a><"+"div id=\'beacon_db6ffb56c1\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=5182&amp;campaignid=1850&amp;zoneid=24&amp;loc=http%3A%2F%2Fcoding.smashingmagazine.com%2F2009%2F09%2F15%2Fthe-z-index-css-property-a-comprehensive-look%2F&amp;referer=http%3A%2F%2Fstackoverflow.com%2Fquestions%2F11856591%2Fhow-to-make-css-menu-stay-on-top&amp;cb=db6ffb56c1\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 10'] = '';
OA_output['spnsr ROS 10'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5985__zoneid=24__OXLCA=1__cb=c559577c94__oadest=http%3A%2F%2Fwww.infragistics.com%2Fproducts%2Findigo-studio%3Futm_source%3DSmashing%2B%26utm_medium%3Dbanner%26utm_content%3D200x125%26utm_campaign%3DIndigo%2BStudio\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=indigo_200x125.jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'Interactive Prototyping Tool\' title=\'Interactive Prototyping Tool\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5985__zoneid=24__OXLCA=1__cb=c559577c94__oadest=http%3A%2F%2Fwww.infragistics.com%2Fproducts%2Findigo-studio%3Futm_source%3DSmashing%2B%26utm_medium%3Dbanner%26utm_content%3D200x125%26utm_campaign%3DIndigo%2BStudio\' target=\'_blank\'>Interactive Prototyping Tool<"+"/a><"+"div id=\'beacon_c559577c94\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=5985&amp;campaignid=2146&amp;zoneid=24&amp;OACBLOCK=86400&amp;OACCAP=4&amp;loc=http%3A%2F%2Fcoding.smashingmagazine.com%2F2009%2F09%2F15%2Fthe-z-index-css-property-a-comprehensive-look%2F&amp;referer=http%3A%2F%2Fstackoverflow.com%2Fquestions%2F11856591%2Fhow-to-make-css-menu-stay-on-top&amp;cb=c559577c94\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 11'] = '';
OA_output['spnsr ROS 11'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5736__zoneid=24__OXLCA=1__cb=741fdf397f__oadest=http%3A%2F%2Fwww.sitefinity.com%2Fcampaigns%2Fwhitepapers%2Fthree-steps-to-a-better-mobile-strategy%3Futm_source%3Dsmashing-magazine%26utm_medium%3Dbanner%26utm_campaign%3Dsmmag_mobilewhitepaper\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=sitefinity_banner_5.jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'Web Content Management.\' title=\'Web Content Management.\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5736__zoneid=24__OXLCA=1__cb=741fdf397f__oadest=http%3A%2F%2Fwww.sitefinity.com%2Fcampaigns%2Fwhitepapers%2Fthree-steps-to-a-better-mobile-strategy%3Futm_source%3Dsmashing-magazine%26utm_medium%3Dbanner%26utm_campaign%3Dsmmag_mobilewhitepaper\' target=\'_blank\'>Web Content Management.<"+"/a><"+"div id=\'beacon_741fdf397f\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=5736&amp;campaignid=2047&amp;zoneid=24&amp;loc=http%3A%2F%2Fcoding.smashingmagazine.com%2F2009%2F09%2F15%2Fthe-z-index-css-property-a-comprehensive-look%2F&amp;referer=http%3A%2F%2Fstackoverflow.com%2Fquestions%2F11856591%2Fhow-to-make-css-menu-stay-on-top&amp;cb=741fdf397f\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 12'] = '';
OA_output['spnsr ROS 12'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=6004__zoneid=24__OXLCA=1__cb=740271a67b__oadest=http%3A%2F%2Fwww.scaletip.com%2Ftip%2F%3Fcc%3Dsm\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=scaletip-smashing-ad.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Give People the Right to Vote\' title=\'Give People the Right to Vote\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=6004__zoneid=24__OXLCA=1__cb=740271a67b__oadest=http%3A%2F%2Fwww.scaletip.com%2Ftip%2F%3Fcc%3Dsm\' target=\'_blank\'>Give People the Right to Vote<"+"/a><"+"div id=\'beacon_740271a67b\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=6004&amp;campaignid=2157&amp;zoneid=24&amp;loc=http%3A%2F%2Fcoding.smashingmagazine.com%2F2009%2F09%2F15%2Fthe-z-index-css-property-a-comprehensive-look%2F&amp;referer=http%3A%2F%2Fstackoverflow.com%2Fquestions%2F11856591%2Fhow-to-make-css-menu-stay-on-top&amp;cb=740271a67b\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 13'] = '';
OA_output['spnsr ROS 13'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5897__zoneid=24__OXLCA=1__cb=bdb418c802__oadest=http%3A%2F%2Fwww.senchacon.com%2F%3Futm_source%3Dwebsite%26utm_medium%3Dsmash%26utm_campaign%3Dsenchacon2013\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=image_11.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Ultimate HTML5 App Dev Event\' title=\'Ultimate HTML5 App Dev Event\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5897__zoneid=24__OXLCA=1__cb=bdb418c802__oadest=http%3A%2F%2Fwww.senchacon.com%2F%3Futm_source%3Dwebsite%26utm_medium%3Dsmash%26utm_campaign%3Dsenchacon2013\' target=\'_blank\'>Ultimate HTML5 App Dev Event<"+"/a><"+"div id=\'beacon_bdb418c802\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=5897&amp;campaignid=2108&amp;zoneid=24&amp;loc=http%3A%2F%2Fcoding.smashingmagazine.com%2F2009%2F09%2F15%2Fthe-z-index-css-property-a-comprehensive-look%2F&amp;referer=http%3A%2F%2Fstackoverflow.com%2Fquestions%2F11856591%2Fhow-to-make-css-menu-stay-on-top&amp;cb=bdb418c802\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 14'] = '';
OA_output['spnsr ROS 14'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5891__zoneid=24__OXLCA=1__cb=8f0ec8295d__oadest=http%3A%2F%2Fwww.zoomyimages.com\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=smag_sponsad_1.4.jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'Quality Stock Images &amp; Music\' title=\'Quality Stock Images &amp; Music\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5891__zoneid=24__OXLCA=1__cb=8f0ec8295d__oadest=http%3A%2F%2Fwww.zoomyimages.com\' target=\'_blank\'>Quality Stock Images &amp; Music<"+"/a><"+"div id=\'beacon_8f0ec8295d\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=5891&amp;campaignid=2104&amp;zoneid=24&amp;loc=http%3A%2F%2Fcoding.smashingmagazine.com%2F2009%2F09%2F15%2Fthe-z-index-css-property-a-comprehensive-look%2F&amp;referer=http%3A%2F%2Fstackoverflow.com%2Fquestions%2F11856591%2Fhow-to-make-css-menu-stay-on-top&amp;cb=8f0ec8295d\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 15'] = '';
OA_output['spnsr ROS 15'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5910__zoneid=24__OXLCA=1__cb=b4f53f2489__oadest=https%3A%2F%2Fwww.creativemarket.com%2Ffree-goods%3Futm_source%3Dsmashing%26utm_medium%3Dbanner%26utm_campaign%3Dsm_fgotw_cm\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=sm_fgotw_cm_3.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Creative Market\' title=\'Creative Market\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5910__zoneid=24__OXLCA=1__cb=b4f53f2489__oadest=https%3A%2F%2Fwww.creativemarket.com%2Ffree-goods%3Futm_source%3Dsmashing%26utm_medium%3Dbanner%26utm_campaign%3Dsm_fgotw_cm\' target=\'_blank\'>Creative Market<"+"/a><"+"div id=\'beacon_b4f53f2489\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=5910&amp;campaignid=2117&amp;zoneid=24&amp;loc=http%3A%2F%2Fcoding.smashingmagazine.com%2F2009%2F09%2F15%2Fthe-z-index-css-property-a-comprehensive-look%2F&amp;referer=http%3A%2F%2Fstackoverflow.com%2Fquestions%2F11856591%2Fhow-to-make-css-menu-stay-on-top&amp;cb=b4f53f2489\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 16'] = '';
OA_output['spnsr ROS 16'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5976__zoneid=24__OXLCA=1__cb=417d938b9e__oadest=http%3A%2F%2Fwww.freshbooks.com%2Fsmashingmag%2F%3Fref%3D9823%26utm_source%3Ddirect%26utm_medium%3Dbanner%26utm_content%3D200x125-static-tryitfree%26utm_campaign%3Dsmashingmag\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=200x125-tryitfree_2.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Invoice like a pro\' title=\'Invoice like a pro\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5976__zoneid=24__OXLCA=1__cb=417d938b9e__oadest=http%3A%2F%2Fwww.freshbooks.com%2Fsmashingmag%2F%3Fref%3D9823%26utm_source%3Ddirect%26utm_medium%3Dbanner%26utm_content%3D200x125-static-tryitfree%26utm_campaign%3Dsmashingmag\' target=\'_blank\'>Invoice like a pro<"+"/a><"+"div id=\'beacon_417d938b9e\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=5976&amp;campaignid=2142&amp;zoneid=24&amp;loc=http%3A%2F%2Fcoding.smashingmagazine.com%2F2009%2F09%2F15%2Fthe-z-index-css-property-a-comprehensive-look%2F&amp;referer=http%3A%2F%2Fstackoverflow.com%2Fquestions%2F11856591%2Fhow-to-make-css-menu-stay-on-top&amp;cb=417d938b9e\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['Sponsor XXL 1'] = '';
OA_output['Sponsor XXL 1'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=5045__zoneid=77__OXLCA=1__cb=2e1f540a32__oadest=http%3A%2F%2Fad.au.doubleclick.net%2Fclk%3B268093556%3B92859839%3Bk\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=410x125-4_2.jpg&contenttype=jpeg\' width=\'410\' height=\'125\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"div id=\'beacon_2e1f540a32\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=5045&amp;campaignid=1794&amp;zoneid=77&amp;loc=http%3A%2F%2Fcoding.smashingmagazine.com%2F2009%2F09%2F15%2Fthe-z-index-css-property-a-comprehensive-look%2F&amp;referer=http%3A%2F%2Fstackoverflow.com%2Fquestions%2F11856591%2Fhow-to-make-css-menu-stay-on-top&amp;cb=2e1f540a32\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['Sponsor XXL 2'] = '';

OA_output['Sponsor XXL 3'] = '';

OA_output['Sponsor XXL 4'] = '';

OA_output['Sponsor XXL 5'] = '';

OA_output['Specials'] = '';

