var DISQUS=function(c){var g=c.DISQUS||{};g.AssertionError=function(b){this.message=b};g.AssertionError.prototype.toString=function(){return"Assertion Error: "+(this.message||"[no message]")};g.assert=function(b,f,e){if(!b)if(e)c.console&&c.console.log("DISQUS assertion failed: "+f);else throw new g.AssertionError(f);};var b=[];g.define=function(d,f){typeof d==="function"&&(f=d,d="");for(var e=d.split("."),h=e.shift(),a=g,l=(f||function(){return{}}).call({overwrites:function(a){a.__overwrites__=!0;
return a}},c);h;)a=a[h]?a[h]:a[h]={},h=e.shift();for(var j in l)l.hasOwnProperty(j)&&(!l.__overwrites__&&a[j]!==null&&g.assert(!a.hasOwnProperty(j),"Unsafe attempt to redefine existing module: "+j,!0),a[j]=l[j],b.push(function(a,b){return function(){delete a[b]}}(a,j)));return a};g.use=function(b){return g.define(b)};g.cleanup=function(){for(var d=0;d<b.length;d++)b[d]()};return g}(window);
DISQUS.define(function(c,g){var b=c.DISQUS,d=c.document,f=d.getElementsByTagName("head")[0]||d.body,e={running:!1,timer:null,queue:[]},h=0;b.getUid=function(a){var b=++h+"";return a?a+b:b};b.defer=function(a,b){function f(){var a=e.queue;if(a.length===0)e.running=!1,clearInterval(e.timer);for(var b=0,l;l=a[b];b++)l[0]()&&(a.splice(b--,1),l[1]())}e.queue.push([a,b]);f();if(!e.running)e.running=!0,e.timer=setInterval(f,100)};b.isOwn=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};b.isString=
function(a){return Object.prototype.toString.call(a)==="[object String]"};b.each=function(a,f){var e=a.length,h=Array.prototype.forEach;if(isNaN(e))for(var d in a)b.isOwn(a,d)&&f(a[d],d,a);else if(h)h.call(a,f);else for(h=0;h<e;h++)f(a[h],h,a)};b.extend=function(a){b.each(Array.prototype.slice.call(arguments,1),function(b){for(var f in b)a[f]=b[f]});return a};b.serializeArgs=function(a){var f=[];b.each(a,function(a,b){a!==g&&f.push(b+(a!==null?"="+encodeURIComponent(a):""))});return f.join("&")};
b.serialize=function(a,f,e){f&&(a+=~a.indexOf("?")?a.charAt(a.length-1)=="&"?"":"&":"?",a+=b.serializeArgs(f));if(e)return f={},f[(new Date).getTime()]=null,b.serialize(a,f);f=a.length;return a.charAt(f-1)=="&"?a.slice(0,f-1):a};b.require=function(a,e,h,c,g){function n(a){if(a.type=="load"||/^(complete|loaded)$/.test(a.target.readyState))c&&c(),q&&clearTimeout(q),b.bean.remove(a.target,r,n)}var o=d.createElement("script"),r=o.addEventListener?"load":"readystatechange",q=null;o.src=b.serialize(a,e,
h);o.async=!0;o.charset="UTF-8";(c||g)&&b.bean.add(o,r,n);g&&(q=setTimeout(function(){g()},2E4));f.appendChild(o);return b};b.requireStylesheet=function(a,e,h){var c=d.createElement("link");c.rel="stylesheet";c.type="text/css";c.href=b.serialize(a,e,h);f.appendChild(c);return b};b.requireSet=function(a,f,e){var h=a.length;b.each(a,function(a){b.require(a,{},f,function(){--h===0&&e()})})};b.injectCss=function(a){var b=d.createElement("style");b.setAttribute("type","text/css");a=a.replace(/\}/g,"}\n");
c.location.href.match(/^https/)&&(a=a.replace(/http:\/\//g,"https://"));b.styleSheet?b.styleSheet.cssText=a:b.appendChild(d.createTextNode(a));f.appendChild(b)};b.isString=function(a){return Object.prototype.toString.call(a)==="[object String]"}});
DISQUS.define("JSON",function(){function c(a){return a<10?"0"+a:a}function g(a){h.lastIndex=0;return h.test(a)?'"'+a.replace(h,function(a){var b=j[a];return typeof b==="string"?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function b(e,h){var c,d,k,n,j=a,p,i=h[e];i&&typeof i==="object"&&typeof i.toJSON==="function"&&!f&&(i=i.toJSON(e));typeof m==="function"&&(i=m.call(h,e,i));switch(typeof i){case "string":return g(i);case "number":return isFinite(i)?String(i):"null";case "boolean":case "null":return String(i);
case "object":if(!i)return"null";a+=l;p=[];if(Object.prototype.toString.apply(i)==="[object Array]"){n=i.length;for(c=0;c<n;c+=1)p[c]=b(c,i)||"null";k=p.length===0?"[]":a?"[\n"+a+p.join(",\n"+a)+"\n"+j+"]":"["+p.join(",")+"]";a=j;return k}if(m&&typeof m==="object"){n=m.length;for(c=0;c<n;c+=1)d=m[c],typeof d==="string"&&(k=b(d,i))&&p.push(g(d)+(a?": ":":")+k)}else for(d in i)Object.hasOwnProperty.call(i,d)&&(k=b(d,i))&&p.push(g(d)+(a?": ":":")+k);k=p.length===0?"{}":a?"{\n"+a+p.join(",\n"+a)+"\n"+
j+"}":"{"+p.join(",")+"}";a=j;return k}}var d={},f=!1;if(typeof Date.prototype.toJSON!=="function")Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+c(this.getUTCMonth()+1)+"-"+c(this.getUTCDate())+"T"+c(this.getUTCHours())+":"+c(this.getUTCMinutes())+":"+c(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()};var e=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
h=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,a,l,j={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},m;d.stringify=function(f,e,h){var c;l=a="";if(typeof h==="number")for(c=0;c<h;c+=1)l+=" ";else typeof h==="string"&&(l=h);if((m=e)&&typeof e!=="function"&&(typeof e!=="object"||typeof e.length!=="number"))throw Error("JSON.stringify");return b("",{"":f})};d.parse=function(a,b){function f(a,
e){var h,c,d=a[e];if(d&&typeof d==="object")for(h in d)Object.hasOwnProperty.call(d,h)&&(c=f(d,h),c!==void 0?d[h]=c:delete d[h]);return b.call(a,e,d)}var h,a=String(a);e.lastIndex=0;e.test(a)&&(a=a.replace(e,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return h=eval("("+a+")"),
typeof b==="function"?f({"":h},""):h;throw new SyntaxError("JSON.parse");};var k={a:[1,2,3]},n,o;if(Object.toJSON&&Object.toJSON(k).replace(/\s/g,"")==='{"a":[1,2,3]}')n=Object.toJSON;typeof String.prototype.evalJSON==="function"&&(k='{"a":[1,2,3]}'.evalJSON(),k.a&&k.a.length===3&&k.a[2]===3&&(o=function(a){return a.evalJSON()}));(function(){var a=[1,2,3];typeof a.toJSON==="function"&&(a=a.toJSON(),f=!(a&&a.length===3&&a[2]===3))})();if(f||!n||!o)return{stringify:d.stringify,parse:d.parse};return{stringify:n,
parse:o}});
DISQUS.define("Bus",function(){function c(b){b=b.split("/");return b[0]+"//"+b[2]}var g=DISQUS.use("JSON"),b=window.location.hash.slice(1),d=window.opener||window.parent,f=document.referrer,e={};e.client=c(document.location.href);e.host=f?c(f):e.client;return{origins:e,messageHandler:function(b){var a;try{a=DISQUS.JSON.parse(b.data)}catch(f){return}if(!a.name||!(a.name[0]==="!"&&b.origin!==e.client))switch(a.scope){case "client":DISQUS.Bus.trigger(a.name,a.data)}},postMessage:function(f){f.sender=b;
f=g.stringify(f);d.postMessage(f,"*")},sendHostMessage:function(b,a){a=a||[];DISQUS.Bus.postMessage({scope:"host",name:b,data:a})},sendGlobalMessage:function(b,a){a=a||[];DISQUS.Bus.postMessage({scope:"global",name:b,data:a})}}});_.extend(DISQUS.Bus,Backbone.Events);
$(document).ready(function(){var c=window.addEventListener?window.addEventListener:window.attachEvent,g=window.addEventListener?"message":"onmessage";if(!c)throw Error("No event support.");c(g,DISQUS.Bus.messageHandler,!1);window.onunload=function(){DISQUS.Bus.sendHostMessage("die")}});
DISQUS.define(function(){var c={apiKey:"E8Uh5l5fHZ6gD8U3KycjAIAk46f68Zw7C6eW8WSjZvCLXebZ7p0r1yrYDrLilk2F",debug:!1,browser:{mobile:/iPhone|Android|iPod|iPad|webOS|Mobile Safari|Windows Phone|BlackBerry|Opera Mini|IEMobile/i.test(navigator.userAgent)}};if(typeof require!=="undefined"&&typeof require==="function")c.bean=require("bean");return c});
DISQUS.define("strings",function(){function c(c){var f=b[c];return f!==void 0?f:c}function g(b,f){return b.replace(/%\(\w+\)s/g,function(e){var e=e.slice(2,-2),c="";e in f?c=f[e]!==void 0&&f[e]!==null?f[e].toString():"":DISQUS.logError&&DISQUS.logError("Key `"+e+"` not found in context for: ",b);return c})}var b={};DISQUS.interpolate=g;DISQUS.modules={};window.gettext=c;return{get:c,interpolate:g,translations:b}});
DISQUS.define("time",function(){return{ISO_8601:"YYYY-MM-DDTHH:mm:ssZ",assureTzOffset:function(c){return c.indexOf("+")>=0?c:c+"+00:00"}}});
DISQUS.define("urls",function(){var c=DISQUS.debug?"/js/src/embed/next/vglnk.js":"/build/next/alfie.js",g=encodeURIComponent(document.referrer),b={root:"http://disqus.com",media:"http://mediacdn.disqus.com/1373499237",translations:"http://mediacdn.disqus.com/1373499237/build/lang",loading:"http://mediacdn.disqus.com/1373499237/html/simple-loading.html",realertime:"",juggler:"",login:"https://disqus.com/next/login/",api:"http://disqus.com/api/3.0/",apiSecure:"https://disqus.com/api/3.0/",logout:"http://disqus.com/logout/?redirect="+
g,editProfile:"http://disqus.com/account/",verifyEmail:"https://disqus.com/next/verify/",authorize:"https://disqus.com/api/oauth/2.0/authorize/",moderate:"http://disqus.com/admin/moderate/",oauth:{twitter:"http://disqus.com/_ax/twitter/begin/",google:"http://disqus.com/_ax/google/begin/",facebook:"http://disqus.com/_ax/facebook/begin/"},avatar:{generic:"http://mediacdn.disqus.com/1373499237/images/noavatar92.png"},linkAffiliatorClient:"http://mediacdn.disqus.com/1373499237"+c};window.location.protocol===
"https:"&&(b=_.extend(b,{root:"https://disqus.com",media:"https://securecdn.disqus.com/1373499237",translations:"https://securecdn.disqus.com/1373499237/build/lang",loading:"/html/simple-loading.html",api:b.apiSecure,logout:"https://disqus.com/logout/?redirect="+g,editProfile:"https://disqus.com/account/",moderate:"https://disqus.com/admin/moderate/",oauth:{twitter:"https://disqus.com/_ax/twitter/begin/",google:"https://disqus.com/_ax/google/begin/",facebook:"http://disqus.com/_ax/facebook/begin/"},
avatar:{generic:"/images/noavatar92.png"},linkAffiliatorClient:""+c}));return b});DISQUS.define("templates",function(){function c(b,c){return Handlebars.partials[b](c||{},{data:g})}var g={urls:DISQUS.urls,gettext:DISQUS.strings.get,sso:null};DISQUS.renderBlock=c;DISQUS.templateGlobals=g;return{globals:g,render:c}});
DISQUS.define("api",function(){function c(b){function e(a){var g=a.originalEvent.origin;DISQUS.urls.apiSecure.slice(0,g.length)===g&&(a=DISQUS.JSON.parse(a.originalEvent.data),a.requestId===c&&(g=a.code===0?b.success:b.error,delete a.requestId,(g||function(){})(a),document.body.removeChild(m),document.body.removeChild(d),$(window).off("message",e)))}var c=_.uniqueId("ft_"),a=document.createElement("div"),d=document.createElement("form"),g="frame_"+c,m;a.innerHTML='<iframe name="'+g+'"></iframe>';
m=a.childNodes[0];d.target=g;d.action=b.url.replace(".json",".pm");d.method=b.method||"GET";b.data=_.extend(b.data,{callback:c,referrer:document.referrer});_.each(b.data,function(a,b){a===!0?a=[1]:a===!1?a=[0]:a===null?a=[""]:_.isArray(a)||(a=[a]);_.each(a,function(a){var c=document.createElement("input");c.type="hidden";c.name=b;c.value=a;d.appendChild(c)})});$(window).on("message",e);document.body.appendChild(m);document.body.appendChild(d);d.submit()}function g(c){c=_.defaults(c,b);c.data=c.data||
{};c.data.api_key=DISQUS.apiKey;return $.ajax(c)}var b={},d={defaults:function(c){var e,d,a;for(e in c)d=c[e],a=b[e],_.isObject(d)&&_.isObject(a)?_.extend(a,d):b[e]=d},headers:function(c){c=_.extend({},b.headers,c);b.headers=_.pick(c,_.map(c,function(b,c){if(b)return c}));return b.headers},getURL:function(b,c){c=c||{};if(c.secure||window.location.protocol==="https:")return DISQUS.urls.apiSecure+b;return DISQUS.urls.api+b},ajax:g,call:function(b,d){d=d||{};d.url=DISQUS.api.getURL(b,{secure:d.secure});
d.data=_.extend(d.data||{},{api_key:DISQUS.apiKey});this.trigger("call",d);var h=(d.secure?c:g)(d);h&&h.always(_.bind(this.trigger,this,"complete"));return h}};_.extend(d,Backbone.Events);return d});
(function(c){var g=DISQUS.Bus,b=DISQUS.api.getURL("internal/switches/list.jsonp");c.switches_jsonp_cb=function(b){g.sendHostMessage("switches.received",b.response)};g.on("fetch",function(c){c=c||{};c.data=c.data||{};c.data.callback="switches_jsonp_cb";c.data.api_key=DISQUS.apiKey;c=DISQUS.serialize(b,c.data,!1);DISQUS.require(c)});g.sendHostMessage("ready")})(this);